version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"

  app:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8888:8888"
    environment:
      DB_HOST: db  
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 1234
    volumes:
      - ./src:/clinic/src
      - ./pom.xml:/clinic/pom.xml
    depends_on:
      - db
volumes:
  pgdata: