version: '3'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .  # Указываем текущий каталог как контекст сборки
      dockerfile: Dockerfile  # Указываем имя Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db  # Используйте имя сервиса в Docker Compose вместо localhost
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
volumes:
  pgdata: